---
sudo: false
dist: xenial
language: ruby
cache: bundler
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.1
env:
  - SKIP_RPC_TESTS=true
before_install: 
  - gem install bundler -v 1.17.3\
  - sudo apt-get update
  - sudo apt-get install -y libsodium-dev
install:
  - git clone https://github.com/bitcoin-core/secp256k1.git && cd secp256k1 && ./autogen.sh && ./configure --enable-module-recovery && make && ./tests && sudo make install && cd ..
  - bundle install
script:
  - bundle exec rake
